# Sidebar navigation

- label: 'Home'
  link: '/'
- label: 'Getting Started'
  link: '/start'
- label: 'ğŸ’ Cherry Emotes'
  items:
    - label: 'Home'
      link: '/emotes'
- label: 'ğŸ± Hellohook'
  items:
    - label: 'Home'
      link: '/hellohook'
- label: 'ğŸ“§ Msgmover'
  items:
    - label: 'Home'
      link: '/msgmover'
- label: 'More cogs'
  items:
    - label: 'bartender'
      link: '/bartender'
    - label: 'coffeetime'
      link: '/coffeetime'
    - label: 'coffeetools'
      link: '/coffeetools'
    - label: 'dmreply'
      link: '/dmreply'
    - label: 'jsonrequest'
      link: '/jsonrequest'
    - label: 'kyarutail'
      link: '/kyarutail'
    - label: 'loveplay'
      link: '/loveplay'
    - label: 'pinboard'
      link: '/pinboard'
    - label: 'quarantine'
      link: '/quarantine'
    - label: 'sendhook'
      link: '/sendhook'
    - label: 'spotifyembed'
      link: '/spotifyembed'
    - label: 'websearch'
      link: '/websearch'

# - label: 'Getting started'
#   link: '/getting-started'
# - label: Usage
#   items:
#     - label: 'Creating docs'
#       link: '/usage/creating-docs'
#     - label: 'Navigation'
#       link: '/usage/navigation'
#     - label: 'Shadowing'
#       link: '/usage/shadowing'
#     - label: 'Using YAML files'
#       link: '/usage/using-yaml-files'
#     - label: 'Remark Plugins'
#       link: '/usage/remark-plugins'
